import { createSlice } from '@reduxjs/toolkit';

// Generated by https://quicktype.io

export interface UserAPIProps {
	id: string;
	email: string;
	nombreUsuario: string;
	plan: string;
	fechaCreacion: string;
	avatar: string;
	googleId: null;
}

export const authSlice = createSlice({
	name: 'auth',
	initialState: {
		userToken: null,
		status: 'not-authenticated',
		nombreUsuario: '',
		isSessionExpiredModalOpen: false,
		isLoading: false,
		isLoadingPerfil: false,
		firstLogin: true,
		usuario: {} as UserAPIProps,
	},
	reducers: {
		start: state => {
			state.status = 'isChecking';
			state.isLoading = true;
		},
		login: (state, { payload }) => {
			state.status = 'authenticated';
			state.nombreUsuario = payload.nombreUsuario;
			state.userToken = payload.token;
			state.isLoading = false;
			state.firstLogin = false;
		},
		register: (state, { payload }) => {
			state.status = 'authenticated';
			state.nombreUsuario = payload.nombreUsuario;
			state.userToken = payload.token;
			state.isLoading = false;
		},
		restoreToken: (state, { payload }) => {
			state.userToken = payload;
			state.status = 'authenticated';
			state.firstLogin = false;
		},
		saveUsername: (state, { payload }) => {
			state.nombreUsuario = payload;
		},
		fail: state => {
			state.status = 'not-authenticated';
			state.isLoading = false;
		},
		signOut: state => {
			state.status = 'not-authenticated';
			state.userToken = null;
			state.nombreUsuario = '';
			state.firstLogin = true;
			state.usuario = {};
			state.isLoading = false;
		},
		tokenExpired: state => {
			state.status = 'not-authenticated';
			state.userToken = null;
			state.nombreUsuario = '';
			state.usuario = {};
		},
		openSessionExpiredModal: state => {
			state.isSessionExpiredModalOpen = true;
		},
		closeSessionExpiredModal: state => {
			state.isSessionExpiredModalOpen = false;
		},
		setFirstLogin: state => {
			state.firstLogin = false;
		},
		// DATOS PERSONALES
		setUsusario: (state, { payload }) => {
			state.usuario = payload;
			// state.isLoading = false;
			// state.status = 'authenticated';
		},
		updateAvatarUsuario: (state, { payload }) => {
			state.usuario.avatar = payload;
		},
		startIsLoading: state => {
			state.isLoadingPerfil = true;
		},
		EndIsLoading: state => {
			state.isLoadingPerfil = false;
		},
	},
});

export const {
	start,
	login,
	register,
	signOut,
	fail,
	restoreToken,
	saveUsername,
	tokenExpired,
	openSessionExpiredModal,
	closeSessionExpiredModal,
	setFirstLogin,
	// DATOS PERSONALES
	setUsusario,
	updateAvatarUsuario,
	// GENERALS
	startIsLoading,
	EndIsLoading,
} = authSlice.actions;
